### ISSUE TITLE
词表建立的问题

### ISSUE THREAD

**Issue by Wxs18337266838** [daniellibin/gaiic2021_track3_querySim#6]
作者你好，你们建立词表的时候只是根据词频阈值过滤掉一些低频次但是没有进行词频对其对吗？
词频对齐的意思是对句子中的词重新进行id分配，将出现频次最高的词对应为最小id（特殊token对应的id除外），将第二高的低频对应的id设置为第二小的id，以此类推。

**Comment by daniellibin** [comment]
是的没有对齐
